// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDasNcpm-gqr8C6NrJs31PqRLRYHuuzlQk',
    appId: '1:848847111211:web:3b5e7f6fd6f283a108d66e',
    messagingSenderId: '848847111211',
    projectId: 'chat-app-5f20c',
    authDomain: 'chat-app-5f20c.firebaseapp.com',
    storageBucket: 'chat-app-5f20c.appspot.com',
    measurementId: 'G-66CLSBEHV2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyApnlm2yJRUax8KDH4DPs2mbFJCfiG8Dn4',
    appId: '1:848847111211:android:be82f222d947128f08d66e',
    messagingSenderId: '848847111211',
    projectId: 'chat-app-5f20c',
    storageBucket: 'chat-app-5f20c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDnxGDIWzd1-QyUwZmYoKrwWYNQjG-TiIU',
    appId: '1:848847111211:ios:7b0deb729e48641008d66e',
    messagingSenderId: '848847111211',
    projectId: 'chat-app-5f20c',
    storageBucket: 'chat-app-5f20c.appspot.com',
    iosBundleId: 'com.example.chatApplication',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDnxGDIWzd1-QyUwZmYoKrwWYNQjG-TiIU',
    appId: '1:848847111211:ios:52609983d64e2f2d08d66e',
    messagingSenderId: '848847111211',
    projectId: 'chat-app-5f20c',
    storageBucket: 'chat-app-5f20c.appspot.com',
    iosBundleId: 'com.example.chatApplication.RunnerTests',
  );
}
